package co.com.prueba.modelo;
// Generated Nov 27, 2020 11:18:46 PM by Hibernate Tools 5.4.21.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TestFactura generated by hbm2java
 */
public class TestFactura implements java.io.Serializable {

	private int idFactura;
	private TestCliente testCliente;
	private Date fechaVenta;
	private BigDecimal valorTotal;
	private Set testFacturaDetalles = new HashSet(0);

	public TestFactura() {
	}

	public TestFactura(int idFactura, TestCliente testCliente, Date fechaVenta, BigDecimal valorTotal) {
		this.idFactura = idFactura;
		this.testCliente = testCliente;
		this.fechaVenta = fechaVenta;
		this.valorTotal = valorTotal;
	}

	public TestFactura(int idFactura, TestCliente testCliente, Date fechaVenta, BigDecimal valorTotal,
			Set testFacturaDetalles) {
		this.idFactura = idFactura;
		this.testCliente = testCliente;
		this.fechaVenta = fechaVenta;
		this.valorTotal = valorTotal;
		this.testFacturaDetalles = testFacturaDetalles;
	}

	public int getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura(int idFactura) {
		this.idFactura = idFactura;
	}

	public TestCliente getTestCliente() {
		return this.testCliente;
	}

	public void setTestCliente(TestCliente testCliente) {
		this.testCliente = testCliente;
	}

	public Date getFechaVenta() {
		return this.fechaVenta;
	}

	public void setFechaVenta(Date fechaVenta) {
		this.fechaVenta = fechaVenta;
	}

	public BigDecimal getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal) {
		this.valorTotal = valorTotal;
	}

	public Set getTestFacturaDetalles() {
		return this.testFacturaDetalles;
	}

	public void setTestFacturaDetalles(Set testFacturaDetalles) {
		this.testFacturaDetalles = testFacturaDetalles;
	}

}
