package co.com.prueba.modelo;
// Generated Nov 27, 2020 11:18:46 PM by Hibernate Tools 5.4.21.Final

import java.math.BigDecimal;

/**
 * TestFacturaDetalle generated by hbm2java
 */
public class TestFacturaDetalle implements java.io.Serializable {

	private int idFacturaDetalle;
	private TestFactura testFactura;
	private TestProducto testProducto;
	private int cantidad;
	private BigDecimal valorUnidad;
	private BigDecimal valorTotal;

	public TestFacturaDetalle() {
	}

	public TestFacturaDetalle(int idFacturaDetalle, TestFactura testFactura, TestProducto testProducto, int cantidad,
			BigDecimal valorUnidad, BigDecimal valorTotal) {
		this.idFacturaDetalle = idFacturaDetalle;
		this.testFactura = testFactura;
		this.testProducto = testProducto;
		this.cantidad = cantidad;
		this.valorUnidad = valorUnidad;
		this.valorTotal = valorTotal;
	}

	public int getIdFacturaDetalle() {
		return this.idFacturaDetalle;
	}

	public void setIdFacturaDetalle(int idFacturaDetalle) {
		this.idFacturaDetalle = idFacturaDetalle;
	}

	public TestFactura getTestFactura() {
		return this.testFactura;
	}

	public void setTestFactura(TestFactura testFactura) {
		this.testFactura = testFactura;
	}

	public TestProducto getTestProducto() {
		return this.testProducto;
	}

	public void setTestProducto(TestProducto testProducto) {
		this.testProducto = testProducto;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public BigDecimal getValorUnidad() {
		return this.valorUnidad;
	}

	public void setValorUnidad(BigDecimal valorUnidad) {
		this.valorUnidad = valorUnidad;
	}

	public BigDecimal getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal) {
		this.valorTotal = valorTotal;
	}

}
